# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redocly.com/docs/cli/ for more information.
api/openapi.bundled.yaml:
  no-server-example.com:
    - '#/servers/0/url'
    - '#/servers/1/url'
    - '#/servers/2/url'
    - '#/paths/~1internal~1sign/servers/0/url'
    - '#/paths/~1internal~1verify/servers/0/url'
    - '#/paths/~1internal~1keys~1rotate/servers/0/url'
  operation-4xx-response:
    - '#/paths/~1vault~1health/get/responses'
    - '#/paths/~1vault~1ready/get/responses'
    - '#/paths/~1vault~1api~1v1~1info/get/responses'
    - '#/paths/~1identity~1.well-known~1did.json/get/responses'
    - '#/paths/~1identity~1health/get/responses'
    - '#/paths/~1identity~1ready/get/responses'
    - '#/paths/~1integrator~1health/get/responses'
    - '#/paths/~1health/get/responses'
    - '#/paths/~1ready/get/responses'
  security-defined:
    - '#/paths/~1vault~1public~1dpp~1{dppId}/get'
    - '#/paths/~1vault~1public~1dpp~1by-gtin~1{gtin}/get'
    - '#/paths/~1vault~1credential~1dpp~1{dppId}/get'
    - '#/paths/~1vault~1health/get'
    - '#/paths/~1vault~1ready/get'
    - '#/paths/~1vault~1api~1v1~1info/get'
    - '#/paths/~1identity~1.well-known~1did.json/get'
    - '#/paths/~1identity~1health/get'
    - '#/paths/~1identity~1ready/get'
    - '#/paths/~1integrator~1health/get'
    - '#/paths/~1integrator~1api~1v1~1templates~1{sector}/get'
    - '#/paths/~1dpp~1{dppId}/get'
    - '#/paths/~1dpp~1{dppId}~1qr/get'
    - '#/paths/~101~1{gtin}/get'
    - '#/paths/~101~1{gtin}~121~1{serial}/get'
    - '#/paths/~101~1{gtin}~110~1{batch}/get'
    - '#/paths/~101~1{gtin}~110~1{batch}~121~1{serial}/get'
    - '#/paths/~1health/get'
    - '#/paths/~1ready/get'
