#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Odal Node — One-Click Installer
# Usage:
#   curl -sSL https://odal-node.io/install.sh | bash
#   curl -sSL https://odal-node.io/install.sh | bash -s -- --no-cli --port 8001
#
# BSL-1.1 License — Copyright (c) 2026 Aleksandar Temelkov (Odal Node) <dev@odal-node.io>
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

# ── Defaults ─────────────────────────────────────────────────────────────────
INSTALL_DIR="${HOME}/.odal"
NODE_PORT=8001
RESOLVER_PORT=8003
INSTALL_CLI=true
COMPOSE_FILE_URL="https://odal-node.io/docker-compose.yml"
ODAL_VERSION="${ODAL_VERSION:-latest}"

# ── Colours ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BOLD='\033[1m'; RESET='\033[0m'

info()  { echo -e "${GREEN}[odal]${RESET} $*"; }
warn()  { echo -e "${YELLOW}[warn]${RESET} $*"; }
error() { echo -e "${RED}[error]${RESET} $*" >&2; exit 1; }

# ── Argument parsing ──────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case $1 in
    --no-cli)    INSTALL_CLI=false; shift ;;
    --port)      NODE_PORT="$2"; shift 2 ;;
    --dir)       INSTALL_DIR="$2"; shift 2 ;;
    --version)   ODAL_VERSION="$2"; shift 2 ;;
    -h|--help)
      echo "Usage: install.sh [--no-cli] [--port PORT] [--dir DIR] [--version VERSION]"
      exit 0 ;;
    *) warn "Unknown flag: $1"; shift ;;
  esac
done

# ── Banner ────────────────────────────────────────────────────────────────────
echo -e "${BOLD}"
echo " ██████╗ ██████╗  █████╗ ██╗          ███╗   ██╗ ██████╗ ██████╗ ███████╗"
echo "██╔═══██╗██╔══██╗██╔══██╗██║          ████╗  ██║██╔═══██╗██╔══██╗██╔════╝"
echo "██║   ██║██║  ██║███████║██║          ██╔██╗ ██║██║   ██║██║  ██║█████╗  "
echo "██║   ██║██║  ██║██╔══██║██║          ██║╚██╗██║██║   ██║██║  ██║██╔══╝  "
echo "╚██████╔╝██████╔╝██║  ██║███████╗     ██║ ╚████║╚██████╔╝██████╔╝███████╗"
echo " ╚═════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝     ╚═╝  ╚═══╝ ╚═════╝ ╚═════╝ ╚══════╝"
echo -e "${RESET}"
echo -e " Digital Product Passport Infrastructure — version ${BOLD}${ODAL_VERSION}${RESET}"
echo

# ── Prerequisite checks ───────────────────────────────────────────────────────
info "Checking prerequisites..."

command -v docker >/dev/null 2>&1 || error "Docker is not installed. See https://docs.docker.com/get-docker/"

if ! docker compose version >/dev/null 2>&1; then
  error "Docker Compose v2 is required. Update Docker Desktop or run: apt install docker-compose-plugin"
fi

DOCKER_VERSION=$(docker version --format '{{.Server.Version}}' 2>/dev/null || echo "unknown")
info "Docker ${DOCKER_VERSION} — OK"
info "Docker Compose — OK"

# ── Create install directory ──────────────────────────────────────────────────
if [[ -d "${INSTALL_DIR}" ]]; then
  warn "Directory ${INSTALL_DIR} already exists — checking for existing installation..."
  IDEMPOTENT=true
else
  mkdir -p "${INSTALL_DIR}"
  IDEMPOTENT=false
fi

cd "${INSTALL_DIR}"

# ── Download docker-compose.yml ───────────────────────────────────────────────
if [[ -f "docker-compose.yml" && "${IDEMPOTENT}" == "true" ]]; then
  warn "docker-compose.yml already exists — skipping download"
else
  info "Downloading docker-compose.yml..."
  if command -v curl >/dev/null 2>&1; then
    curl -sSL "${COMPOSE_FILE_URL}" -o docker-compose.yml
  elif command -v wget >/dev/null 2>&1; then
    wget -qO docker-compose.yml "${COMPOSE_FILE_URL}"
  else
    error "Neither curl nor wget is available. Install one and retry."
  fi
fi

# ── Generate secrets ──────────────────────────────────────────────────────────
generate_secret() {
  if [[ -r /dev/urandom ]]; then
    tr -dc 'A-Za-z0-9' </dev/urandom | head -c 32
  else
    openssl rand -hex 16
  fi
}

if [[ -f ".env" && "${IDEMPOTENT}" == "true" ]]; then
  warn ".env already exists — reusing existing secrets"
  set -a; source .env; set +a
else
  info "Generating secrets..."
  DB_PASS=$(generate_secret)
  KS_PASS=$(generate_secret)
  API_KEY="odal_sk_$(generate_secret)"

  cat > .env <<EOF
# Odal Node — generated by install.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')
# Keep this file secret — do not commit it to version control.

DATABASE_URL=postgres://odal_app:${DB_PASS}@postgres:5432/odal
DATABASE_MIGRATE_URL=postgres://postgres:${DB_PASS}@postgres:5432/odal

PORT=${NODE_PORT}
RESOLVER_PORT=${RESOLVER_PORT}

KEY_STORE_PATH=keystore.enc
KEY_STORE_PASSPHRASE=${KS_PASS}
DID_WEB_BASE_URL=http://localhost:${NODE_PORT}

JWKS_URL=
JWT_AUDIENCE=odal-api
JWT_ISSUER=

CORS_ALLOWED_ORIGINS=

LOG_LEVEL=info
PLUGINS_DIR=/plugins
BATCH_CONCURRENCY=20
EOF
  info ".env created with generated secrets"
fi

# ── Start services ────────────────────────────────────────────────────────────
info "Starting Odal Node services..."
docker compose up -d

# ── Health poll ───────────────────────────────────────────────────────────────
poll_health() {
  local service="$1"
  local url="$2"
  local max_attempts=30
  local attempt=0
  local delay=3

  printf "  Waiting for %s to become healthy " "${service}"
  while (( attempt < max_attempts )); do
    if curl -fs "${url}" >/dev/null 2>&1; then
      echo -e " ${GREEN}OK${RESET}"
      return 0
    fi
    printf "."
    sleep "${delay}"
    (( attempt++ ))
  done
  echo -e " ${RED}TIMEOUT${RESET}"
  return 1
}

NODE_URL="http://localhost:${NODE_PORT:-8001}"
RESOLVER_URL="http://localhost:${RESOLVER_PORT:-8003}"

info "Waiting for services to become healthy..."
poll_health "node"     "${NODE_URL}/health"     || error "Node failed to become healthy. Run: docker compose logs node"
poll_health "resolver" "${RESOLVER_URL}/health" || warn  "Resolver health check timed out (may still be starting)"

# ── Install odal CLI (optional) ─────────────────────────────────────────────
if [[ "${INSTALL_CLI}" == "true" ]]; then
  if command -v odal >/dev/null 2>&1; then
    info "odal CLI already installed ($(odal --version 2>/dev/null || echo 'unknown version'))"
  else
    info "Installing odal CLI..."
    if command -v cargo >/dev/null 2>&1; then
      cargo install odal-cli --quiet 2>/dev/null && info "odal CLI installed via cargo" || warn "cargo install failed — skipping CLI"
    else
      ARCH=$(uname -m)
      OS=$(uname -s | tr '[:upper:]' '[:lower:]')
      BIN_URL="https://github.com/odal-node/dpp-engine/releases/download/${ODAL_VERSION}/odal-${OS}-${ARCH}"
      if command -v curl >/dev/null 2>&1; then
        if curl -sSLf "${BIN_URL}" -o /tmp/odal 2>/dev/null; then
          chmod +x /tmp/odal
          sudo mv /tmp/odal /usr/local/bin/odal 2>/dev/null || mv /tmp/odal "${HOME}/.local/bin/odal"
          info "odal CLI installed to /usr/local/bin/odal"
        else
          warn "Pre-built binary not available for ${OS}/${ARCH} — install manually with: cargo install odal-cli"
        fi
      fi
    fi
  fi
fi

# ── Summary ───────────────────────────────────────────────────────────────────
echo
echo -e "${BOLD}═══════════════════════════════════════════════════════${RESET}"
echo -e "${BOLD}  Odal Node installation complete!${RESET}"
echo -e "${BOLD}═══════════════════════════════════════════════════════${RESET}"
echo
echo -e "  Node API    : ${GREEN}${NODE_URL}${RESET}"
echo -e "    Vault     : ${NODE_URL}/vault"
echo -e "    Identity  : ${NODE_URL}/identity"
echo -e "    Integrator: ${NODE_URL}/integrator"
echo -e "  Resolver    : ${GREEN}${RESOLVER_URL}${RESET}"
echo -e "  Install dir : ${INSTALL_DIR}"
echo
if [[ -n "${API_KEY:-}" ]]; then
  echo -e "  ${BOLD}API Key${RESET}: ${YELLOW}${API_KEY}${RESET}"
  echo -e "  (saved to ${INSTALL_DIR}/.env — keep this secret)"
  echo
fi
echo -e "  Next steps:"
echo -e "    odal status          — verify all services are healthy"
echo -e "    odal import data.csv — import product passports"
echo
echo -e "  Docs: https://docs.odal-node.io"
echo
